import 'package:flutter_riverpod/flutter_riverpod.dart';
import 'package:uuid/uuid.dart';

import '../models/loan_contact.dart';
import '../models/loan_transaction.dart';
import '../models/saving_goal.dart';
import '../models/wallet.dart';
import '../providers/loan_provider.dart';
import '../providers/saving_goal_provider.dart';
import '../providers/transaction_provider.dart';
import '../providers/wallet_provider.dart';

/// Result summary returned after dispatching AI actions.
class AiDispatchResult {
  final bool isSuccess;
  final String summaryMessage;
  final int transactionsCount;
  final int transfersCount;
  final int loansCount;
  final int goalsCount;

  AiDispatchResult({
    required this.isSuccess,
    required this.summaryMessage,
    this.transactionsCount = 0,
    this.transfersCount = 0,
    this.loansCount = 0,
    this.goalsCount = 0,
  });
}

/// Dispatches structured actions generated by AI into respective app providers.
class AiActionDispatcher {
  /// Executes all parsed actions and returns a human-readable summary.
  static Future<AiDispatchResult> dispatch({
    required WidgetRef ref,
    required Map<String, dynamic> aiResult,
    required List<Wallet> availableWallets,
    required List<LoanContact> availableLoanContacts,
    required List<SavingGoal> availableSavingGoals,
  }) async {
    final actions = aiResult['actions'] as List<dynamic>? ?? [];

    // Fallback to legacy 'transactions' array if 'actions' is empty
    if (actions.isEmpty && aiResult.containsKey('transactions')) {
      final legacyTx = aiResult['transactions'] as List<dynamic>? ?? [];
      for (final tx in legacyTx) {
        actions.add({
          'actionType': 'transaction',
          'amount': tx['amount'],
          'type': tx['type'],
          'note': tx['note'],
          'categoryId': tx['categoryId'],
          'walletId': tx['walletId'],
          'date': tx['date'],
        });
      }
    }

    if (actions.isEmpty) {
      return AiDispatchResult(
        isSuccess: false,
        summaryMessage: 'Không có hành động nào được nhận diện.',
      );
    }

    // Default fallback wallet
    final defaultWalletId = availableWallets.isNotEmpty
        ? (availableWallets.where((w) => w.isDefault).firstOrNull?.id ?? availableWallets.first.id)
        : null;

    int txCount = 0;
    int transferCount = 0;
    int loanCount = 0;
    int goalCount = 0;

    final List<Map<String, dynamic>> newTransactions = [];

    for (final action in actions) {
      if (action is! Map<String, dynamic>) continue;

      final actionType = action['actionType'] as String? ?? 'transaction';
      final double amount = (action['amount'] as num?)?.toDouble() ?? 0.0;
      if (amount <= 0) continue;

      final dateStr = action['date'] as String?;
      final date = dateStr != null ? (DateTime.tryParse(dateStr) ?? DateTime.now()) : DateTime.now();
      final note = action['note'] as String? ?? '';

      switch (actionType) {
        case 'transaction':
          final type = action['type'] as String? ?? 'expense';
          final categoryId = action['categoryId'] as String?;
          final walletId = action['walletId'] as String? ?? defaultWalletId;

          newTransactions.add({
            'categoryId': categoryId,
            'walletId': walletId,
            'amount': amount,
            'note': note,
            'type': type,
            'transactionDate': date,
          });
          txCount++;
          break;

        case 'transfer':
          String? sourceId = action['sourceWalletId'] as String?;
          String? destId = action['destinationWalletId'] as String?;

          // Validate or fallback wallets
          if (sourceId == null && availableWallets.isNotEmpty) {
            sourceId = defaultWalletId;
          }
          if (destId == null && availableWallets.length > 1) {
            destId = availableWallets.firstWhere((w) => w.id != sourceId).id;
          }

          if (sourceId != null && destId != null && sourceId != destId) {
            final double fee = (action['fee'] as num?)?.toDouble() ?? 0.0;
            await ref.read(walletProvider.notifier).transferFunds(
                  sourceWalletId: sourceId,
                  destinationWalletId: destId,
                  amount: amount,
                  fee: fee,
                  transferDate: date,
                  note: note.isNotEmpty ? note : 'Chuyển ví qua trợ lý AI',
                );
            transferCount++;
          }
          break;

        case 'loan_create':
          final loanType = action['loanType'] as String? ?? 'lent';
          final contactName = (action['contactName'] as String?)?.trim() ?? 'Người quen';
          final contactId = action['contactId'] as String?;

          // Check if contact already exists
          LoanContact? existingContact;
          if (contactId != null) {
            existingContact = availableLoanContacts.where((l) => l.id == contactId).firstOrNull;
          }
          existingContact ??= availableLoanContacts.where(
            (l) => l.contactName.toLowerCase() == contactName.toLowerCase() && l.type == loanType,
          ).firstOrNull;

          if (existingContact != null) {
            final double newRemaining = existingContact.remainingAmount + amount;
            final double newTotal = existingContact.totalAmount + amount;
            final updated = existingContact.copyWith(
              remainingAmount: newRemaining,
              totalAmount: newTotal,
              status: 'active',
            );
            await ref.read(loanProvider.notifier).updateLoanContact(updated);

            final loanTx = LoanTransaction(
              id: const Uuid().v4(),
              loanId: existingContact.id,
              amount: amount,
              type: loanType,
              date: date,
              note: note.isNotEmpty ? note : 'Tạo thêm khoản nợ qua AI',
            );
            await ref.read(loanRepositoryProvider).insertLoanTransaction(loanTx);
          } else {
            final newContact = LoanContact(
              id: const Uuid().v4(),
              contactName: contactName,
              type: loanType,
              totalAmount: amount,
              remainingAmount: amount,
              status: 'active',
            );
            await ref.read(loanProvider.notifier).addLoanContact(newContact);

            final loanTx = LoanTransaction(
              id: const Uuid().v4(),
              loanId: newContact.id,
              amount: amount,
              type: loanType,
              date: date,
              note: note.isNotEmpty ? note : 'Khởi tạo khoản nợ qua AI',
            );
            await ref.read(loanRepositoryProvider).insertLoanTransaction(loanTx);
          }
          loanCount++;
          break;

        case 'loan_repay':
          final repayType = action['repayType'] as String? ?? 'repay';
          final contactName = (action['contactName'] as String?)?.trim();
          final contactId = action['contactId'] as String?;

          LoanContact? contact;
          if (contactId != null) {
            contact = availableLoanContacts.where((l) => l.id == contactId).firstOrNull;
          }
          if (contact == null && contactName != null) {
            contact = availableLoanContacts.where(
              (l) => l.contactName.toLowerCase() == contactName.toLowerCase(),
            ).firstOrNull;
          }

          if (contact != null) {
            final double newRemaining = (contact.remainingAmount - amount).clamp(0.0, double.infinity);
            final updated = contact.copyWith(
              remainingAmount: newRemaining,
              status: newRemaining <= 0 ? 'settled' : 'active',
            );
            await ref.read(loanProvider.notifier).updateLoanContact(updated);

            final loanTx = LoanTransaction(
              id: const Uuid().v4(),
              loanId: contact.id,
              amount: amount,
              type: repayType,
              date: date,
              note: note.isNotEmpty ? note : (repayType == 'collect' ? 'Thu nợ qua AI' : 'Trả nợ qua AI'),
            );
            await ref.read(loanRepositoryProvider).insertLoanTransaction(loanTx);
            loanCount++;
          }
          break;

        case 'goal_deposit':
        case 'goal_withdraw':
          final isDeposit = actionType == 'goal_deposit';
          final goalId = action['goalId'] as String?;
          final goalName = (action['goalName'] as String?)?.trim();

          SavingGoal? goal;
          if (goalId != null) {
            goal = availableSavingGoals.where((g) => g.id == goalId).firstOrNull;
          }
          if (goal == null && goalName != null) {
            goal = availableSavingGoals.where(
              (g) => g.name.toLowerCase().contains(goalName.toLowerCase()),
            ).firstOrNull;
          }

          if (goal != null) {
            await ref.read(savingGoalProvider.notifier).addLog(
                  goalId: goal.id,
                  amount: amount,
                  type: isDeposit ? 'deposit' : 'withdraw',
                  logDate: date,
                  note: note.isNotEmpty ? note : (isDeposit ? 'Góp quỹ qua AI' : 'Rút quỹ qua AI'),
                );
            goalCount++;
          }
          break;
      }
    }

    // Execute standard transactions in batch
    if (newTransactions.isNotEmpty) {
      await ref.read(transactionProvider.notifier).createTransactions(newTransactions);
    }

    // Build human-friendly summary message in Vietnamese
    final parts = <String>[];
    if (txCount > 0) parts.add('$txCount giao dịch thu/chi');
    if (transferCount > 0) parts.add('$transferCount chuyển khoản ví');
    if (loanCount > 0) parts.add('$loanCount khoản nợ');
    if (goalCount > 0) parts.add('$goalCount mục tiêu tiết kiệm');

    final summary = parts.isEmpty
        ? 'Đã xử lý xong yêu cầu của bạn!'
        : 'Đã ghi nhận: ${parts.join(', ')}!';

    return AiDispatchResult(
      isSuccess: true,
      summaryMessage: summary,
      transactionsCount: txCount,
      transfersCount: transferCount,
      loansCount: loanCount,
      goalsCount: goalCount,
    );
  }
}
